version: "3.5"
services:
  beacon-chain:
    build:
      context: ./beacon-chain
      args:
        BEACON_API_PORT: 3500
        UPSTREAM_VERSION: 24.3.1
    environment:
      BEACON_API_PORT: 3500
      CHECKPOINT_SYNC_URL: ""
      P2P_PORT: 9105
      FEE_RECIPIENT_ADDRESS: ""
      EXTRA_OPTS: ""
      JAVA_OPTS: "-Xmx6g"
    volumes:
      - "teku-data:/opt/teku/data"
    ports:
      - "9105:9105/tcp"
      - "9105:9105/udp"
    restart: unless-stopped
    image: "beacon-chain.teku.dnp.dappnode.eth:0.1.0"
    security_opt:
      - "seccomp:unconfined"
  validator:
    build:
      context: ./validator
      args:
        UPSTREAM_VERSION: 24.3.1
    environment:
      LOG_TYPE: INFO
      BEACON_NODE_ADDR: "http://beacon-chain.teku.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      EXIT_VALIDATOR: ""
      KEYSTORES_VOLUNTARY_EXIT: ""
      FEE_RECIPIENT_ADDRESS: ""
      JAVA_OPTS: "-Xmx6g"
    restart: unless-stopped
    image: "validator.teku.dnp.dappnode.eth:0.1.0"
    security_opt:
      - "seccomp:unconfined"
volumes:
  teku-data: {}
